# Copyright (c) 2026 Wind River Systems, Inc.

BB_CONF_FRAGMENT_SUMMARY = "Enable the tasklogger bbclass"
BB_CONF_FRAGMENT_DESCRIPTION = "Enable the tasklogger bbclass \
  - Inherits tasklogger globally, provided by the separate meta-tasklogger layer. \
"

INHERIT += "tasklogger"
